apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/appdb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"